### ISSUE TITLE
Base table or view not found when using a database prefix

### ISSUE THREAD

**Issue by ebesh** [awssat/laravel-sync-migration#1]
Hi,

Thanks for your great idea.
I have a small issue with laravel-sync-migration in a project which uses database prefixes (parameter "prefix" in database config).

In my case, here is my config line for mysql : 
`'prefix' => 'age_',`

When I launch the command 
`php artisan migrate:sync`

I have the following error : 
`Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'agence_a.users' doesn't exist (SQL: DESCRIBE users)`

where `'agence_a.users'` should be `'agence_a.age_users'`

Not sure of the way to fix it, some help will be welcolme ;)

Thanks a lot.

**Comment by BSN4** [comment]
Thanks for reporting I'll push a fix soon
