### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed error running in sail/docker

### ISSUE THREAD

**Issue by jayenne** [awssat/laravel-sync-migration#11]
I'm not sure why but wonder if it's conected to runnning under laravel/sail docker (mariadb) where my DB_HOST is not localhost but mariadb instead?

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (SQL: select * from information_schema.tables where table_schema = mydb and table_name = users and table_type = 'BASE TABLE')

**Comment by abdumu** [comment]
This is a very interesting issue!

Can you provide us with the steps to produce such an error?

**Comment by jayenne** [comment]
I can test my hypothosis later but but my stack showing this error is..
install a fresh laravel jetstream sail with mariaDB using livewire / alpinejs
config the env/config
spin sail up
install laravel-sync-migration
see error

*I'll perform this myself later and see if i can isolate it to docker or database

**Comment by abdumu** [comment]
since there is no update about this issue, i'll close it for now.
