### ISSUE TITLE
laravel 7 support still exists comments bug

### ISSUE THREAD

**Issue by yuhal** [awssat/laravel-sync-migration#14]
Hello~ awssat. laravel 7 support still exists comments bug, Please release the package that generally supports laravel 7. Thank you~

**Comment by BSN4** [comment]
last version doesn't work with laravel 7 ?

**Comment by yuhal** [comment]
Yes, I am using laravel 7. I tried to update the package to version 3.0.1 and returned the following error:




Problem 1
   - Root composer.json requires awssat/laravel-sync-migration 3.0.1 -> satisfiable by awssat/laravel-sync-migration[v3.0.1].
   - awssat/laravel-sync-migration v3.0.1 requires doctrine/dbal ^3.0 -> found doctrine/dbal[3.0.0, ..., 3.4.x-dev] but it conflicts with your root composer.json require (^2.9).




| |
HaI
|
|
***@***.***
|
签名由网易邮箱大师定制


On 03/3/2022 17:51，Bader ***@***.***> wrote：

last version doesn't work with laravel 7 ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BSN4** [comment]
well you need to upgrade to laravel 8

**Comment by yuhal** [comment]
Okay, I'll try to upgrade.
