### ISSUE TITLE
Facing Issue in Installation for Laravel 9

### ISSUE THREAD

**Issue by MustafaGondalwala** [awssat/laravel-sync-migration#15]
I am not able to install package in laravel 9
Getting Error like this

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - awssat/laravel-sync-migration[v3.0, ..., v3.0.1] require illuminate/support 5.0 - 5.8 | ^6.0 | ^7.0 | ^8.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires awssat/laravel-sync-migration ^3.0 -> satisfiable by awssat/laravel-sync-migration[v3.0, v3.0.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require awssat/laravel-sync-migration:*" to figure out if any version is installable, or "composer require awssat/laravel-sync-migration:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by MustafaGondalwala** [comment]
Here my composer.json
"require": {
        "php": "^8.0.2",
        "arcanedev/log-viewer": "^9.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.11",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^3.4",
        "maatwebsite/excel": "^3.1",
        "phpoffice/phpspreadsheet": "^1.23",
        "rahulhaque/laravel-filepond": "^1.8",
        "spatie/laravel-medialibrary": "^10.3",
        "spatie/laravel-permission": "^5.5",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },

**Comment by if4lcon** [comment]
No Laravel 9 support at moment feel free to post a PR

**Comment by BSN4** [comment]
we support Laravel 9 now
