### ISSUE TITLE
Getting error composer install

### ISSUE THREAD

**Issue by khanakia** [awssat/laravel-sync-migration#18]
```sh
✗ composer require awssat/laravel-sync-migration
./composer.json has been updated
Running composer update awssat/laravel-sync-migration
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - awssat/laravel-sync-migration[0.1, ..., 0.1.3] require php ~5.6|~7.0 -> your php version (8.1.27) does not satisfy that requirement.
    - awssat/laravel-sync-migration[0.1.4, ..., 0.2.0] require php ~7.1 -> your php version (8.1.27) does not satisfy that requirement.
    - awssat/laravel-sync-migration[v3.0, ..., v3.0.1] require illuminate/support 5.0 - 5.8 | ^6.0 | ^7.0 | ^8.0 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - awssat/laravel-sync-migration 4.0.0 requires illuminate/support ~5.5.0 || ~5.6.0 || ~5.7.0 || ~5.8.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires awssat/laravel-sync-migration * -> satisfiable by awssat/laravel-sync-migration[0.1, ..., 0.2.0, v3.0, v3.0.1, 4.0.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require awssat/laravel-sync-migration:*" to figure out if any version is installable, or "composer require awssat/laravel-sync-migration:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by alexworldbr** [comment]
Hi folks,

I have the same error on php 8.1 and laravel 11.

How to solve it?

**Comment by BSN4** [comment]
@APMU sorry I don't have time to update the repo dependencies .. feel free to open PR.

**Comment by BSN4** [comment]
@APMU can you try now?

**Comment by alexworldbr** [comment]
> @APMU can you try now?

Hi @BSN4! Thanks for reply.

Excuse me, but Laravel 11 requires php 8.2 or 8.3. Not 8.1 as i said.

The your latest PR was version 3.0.2, but there are a previous 4.0.0 vesion.

A new test with Lavel 11 and php 8.3 yet show errors:

> ./composer.json has been updated
> Running composer update awssat/laravel-sync-migration
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 

> Problem 1
>     - Root composer.json requires awssat/laravel-sync-migration 3.0.2 -> satisfiable by awssat/laravel-sync-migration[v3.0.2].
>     - carbonphp/carbon-doctrine-types 3.2.0 conflicts with doctrine/dbal 3.9.3.
>     - awssat/laravel-sync-migration v3.0.2 requires doctrine/dbal ^3.4 -> satisfiable by doctrine/dbal[3.4.0, ..., 3.9.3].
>     - nesbot/carbon 3.8.0 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.2.0].
>     - symfony/http-foundation v7.1.5 conflicts with doctrine/dbal 3.5.4.
>     - symfony/http-foundation v7.1.5 conflicts with doctrine/dbal 3.4.6.
>     - laravel/framework v11.29.0 requires nesbot/carbon ^2.72.2|^3.0 -> satisfiable by nesbot/carbon[3.8.0].
>     - laravel/framework v11.29.0 requires symfony/http-foundation ^7.0 -> satisfiable by symfony/http-foundation[v7.1.5].
>     - laravel/framework is locked to version v11.29.0 and an update of this package was not requested.
> 
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.


Can verifiy? Thanks.

**Comment by BSN4** [comment]
@abdumu can you check this out please

**Comment by alexworldbr** [comment]
> @abdumu can you check this out please

@BSN4 the error now is "doctrine/dbal ^3.4"

Can verify it?

**Comment by alexworldbr** [comment]
Hi, 

No more errors after:

"composer require awssat/laravel-sync-migration **-W**"
