### ISSUE TITLE
Can't install in Laravel 8

### ISSUE THREAD

**Issue by timmy1420** [awssat/laravel-sync-migration#8]
Can't install this package in existing Laravel 8 project. Even in a fresh Laravel 8 installation.

# Terminal output:

Running composer update awssat/laravel-sync-migration
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires awssat/laravel-sync-migration ^0.2.0 -> satisfiable by awssat/laravel-sync-migration[0.2.0].
    - awssat/laravel-sync-migration 0.2.0 requires illuminate/support 5.6.* || 5.7.* || 5.8.* || ^6.0|| ^7.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.

# Composer.json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.5",
        "laravel/framework": "^8.12",
        "laravel/passport": "^10.1",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "maatwebsite/excel": "^3.1",
        "propaganistas/laravel-disposable-email": "^2.1",
        "rennokki/laravel-eloquent-query-cache": "^2.6",
        "sentry/sentry-laravel": "^2.5"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by BSN4** [comment]
can you make a PR ? it's simple just update composer.json

**Comment by abdumu** [comment]
@if4lcon which values ?

**Comment by timmy1420** [comment]
> can you make a PR ? it's simple just update composer.json

Alright
